services:
  db:
    image: postgres:16
    container_name: ml_postgres
    restart: always
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
  
  redis:
    image: redis:alpine
    container_name: redis_broker
    restart: always
    ports: ["6379:6379"]

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow_server
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GUNICORN_CMD_ARGS: "--forwarded-allow-ips='*'"
    command:
      [
        "mlflow",
        "server",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--allowed-hosts",
        "localhost,localhost:5000,127.0.0.1,127.0.0.1:5000,mlflow,mlflow:5000,*",
        "--backend-store-uri",
        "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}",
        "--default-artifact-root",
        "mlflow-artifacts:/",
        "--artifacts-destination",
        "file:/mlartifacts",
      ]
    ports:
      - "5001:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/').read(); print('ok')"]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genre_api
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      MLFLOW_TRACKING_URI: http://mlflow:5000
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8001:8000"
    volumes:
      - ./mlartifacts:/mlartifacts:ro
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_healthy
      redis: 
        condition: service_started

  worker:
    build: { context: ., dockerfile: Dockerfile } # Uses the same image as your API
    container_name: ml_worker
    restart: always
    env_file: [.env]
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MLFLOW_TRACKING_URI: http://mlflow:5000
      # NEW: Worker needs to know where the broker (Redis) is
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    # CHANGED: Command runs Celery instead of Uvicorn
    command: ["python", "-m","celery", "-A", "tasks", "worker", "--loglevel=info", "--concurrency=1"]
    volumes: ["./mlartifacts:/mlartifacts:ro"] # Worker needs access to models
    depends_on:
      db: { condition: service_healthy }
      mlflow: { condition: service_healthy }
      redis: { condition: service_started }

volumes:
  pgdata:
