services:
  db:
    image: postgres:15
    container_name: ml_postgres
    restart: always
    environment:
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpass
      POSTGRES_DB: mldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jupyter:
    build: .
    container_name: ml_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata: